import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#081225',
  },
  container: {
    flex: 1,
    backgroundColor: '#081225',
  },
  welcomeScroll: {
    padding: 20,
    alignItems: 'center',
  },
  logoContainer: {
    alignItems: 'center',
    marginVertical: 40,
  },
  logoSub: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#E5A93C',
    letterSpacing: 4,
  },
  logoTitle: {
    fontSize: 38,
    fontWeight: '900',
    color: '#FFFFFF',
    marginTop: 5,
    textShadowColor: 'rgba(229, 169, 60, 0.4)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 6,
  },
  divider: {
    width: 60,
    height: 4,
    backgroundColor: '#E5A93C',
    borderRadius: 2,
    marginVertical: 15,
  },
  quoteText: {
    fontSize: 14,
    fontStyle: 'italic',
    color: '#8A99AD',
    textAlign: 'center',
    paddingHorizontal: 30,
  },
  card: {
    width: '100%',
    backgroundColor: '#162239',
    borderRadius: 16,
    padding: 20,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#24344F',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 5,
  },
  cardHeaderTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 15,
  },
  categoriesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 10,
  },
  categoryButton: {
    width: '48%',
    backgroundColor: '#0D192C',
    paddingVertical: 12,
    paddingHorizontal: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#24344F',
    alignItems: 'center',
    marginBottom: 2,
  },
  categoryButtonActive: {
    backgroundColor: '#E5A93C20',
    borderColor: '#E5A93C',
  },
  categoryBtnText: {
    color: '#A0AEC0',
    fontSize: 13,
    fontWeight: '600',
  },
  categoryBtnTextActive: {
    color: '#E5A93C',
  },
  countContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
  },
  countButton: {
    flex: 1,
    backgroundColor: '#0D192C',
    paddingVertical: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#24344F',
    alignItems: 'center',
  },
  countButtonActive: {
    backgroundColor: '#E5A93C20',
    borderColor: '#E5A93C',
  },
  countBtnText: {
    color: '#A0AEC0',
    fontSize: 14,
    fontWeight: '600',
  },
  countBtnTextActive: {
    color: '#E5A93C',
  },
  primaryButton: {
    width: '100%',
    backgroundColor: '#E5A93C',
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 10,
    shadowColor: '#E5A93C',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 4,
  },
  primaryButtonText: {
    color: '#081225',
    fontSize: 16,
    fontWeight: 'bold',
    letterSpacing: 1,
  },
  gameContainer: {
    flex: 1,
    padding: 20,
    justifyContent: 'space-between',
  },
  gameHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  questionProgress: {
    color: '#8A99AD',
    fontSize: 14,
    fontWeight: '600',
  },
  categoryBadge: {
    color: '#E5A93C',
    fontSize: 12,
    fontWeight: 'bold',
    textTransform: 'uppercase',
    marginTop: 2,
  },
  timerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#E5A93C15',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E5A93C40',
  },
  timerContainerAlert: {
    backgroundColor: '#ff525215',
    borderColor: '#ff525240',
  },
  timerText: {
    color: '#E5A93C',
    fontWeight: 'bold',
    fontSize: 14,
    marginLeft: 5,
  },
  timerTextAlert: {
    color: '#ff5252',
  },
  progressTrack: {
    height: 6,
    backgroundColor: '#24344F',
    borderRadius: 3,
    width: '100%',
    marginBottom: 20,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: '#E5A93C',
    borderRadius: 3,
  },
  scrollQuizContent: {
    flexGrow: 1,
    paddingBottom: 20,
  },
  questionCard: {
    backgroundColor: '#162239',
    borderRadius: 16,
    padding: 24,
    minHeight: 130,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#24344F',
  },
  questionText: {
    color: '#FFFFFF',
    fontSize: 19,
    fontWeight: '700',
    textAlign: 'center',
    lineHeight: 28,
  },
  optionsList: {
    gap: 12,
    marginBottom: 20,
  },
  optionItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#162239',
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#24344F',
  },
  optionItemText: {
    color: '#E2E8F0',
    fontSize: 16,
    fontWeight: '500',
    flex: 1,
    marginRight: 10,
  },
  optionCorrect: {
    backgroundColor: '#1B3E2C',
    borderColor: '#4cd137',
  },
  optionIncorrect: {
    backgroundColor: '#3E1C1C',
    borderColor: '#ff5252',
  },
  optionDimmed: {
    opacity: 0.4,
  },
  optionTextCorrect: {
    color: '#4cd137',
    fontWeight: 'bold',
  },
  optionTextIncorrect: {
    color: '#ff5252',
    fontWeight: 'bold',
  },
  explanationCard: {
    backgroundColor: '#1D2A44',
    padding: 16,
    borderRadius: 12,
    borderLeftWidth: 4,
    borderLeftColor: '#E5A93C',
    marginTop: 10,
  },
  explanationHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  explanationHeaderTitle: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 14,
  },
  explanationText: {
    color: '#A0AEC0',
    fontSize: 14,
    lineHeight: 20,
  },
  resultsHeader: {
    alignItems: 'center',
    marginVertical: 30,
    width: '100%',
  },
  rankEmoji: {
    fontSize: 70,
    marginBottom: 10,
  },
  resultsSubtitle: {
    color: '#8A99AD',
    fontSize: 13,
    fontWeight: 'bold',
    letterSpacing: 2,
    marginBottom: 5,
  },
  rankTitle: {
    color: '#E5A93C',
    fontSize: 26,
    fontWeight: '900',
    textAlign: 'center',
    marginBottom: 15,
  },
  scoreContainer: {
    flexDirection: 'row',
    alignItems: 'baseline',
    backgroundColor: '#162239',
    paddingVertical: 10,
    paddingHorizontal: 24,
    borderRadius: 30,
    borderWidth: 1,
    borderColor: '#24344F',
    marginBottom: 20,
  },
  scoreValue: {
    color: '#FFFFFF',
    fontSize: 36,
    fontWeight: 'bold',
  },
  scoreMax: {
    color: '#8A99AD',
    fontSize: 18,
    fontWeight: '600',
  },
  rankDescription: {
    color: '#D2D9E4',
    fontSize: 15,
    textAlign: 'center',
    lineHeight: 22,
    paddingHorizontal: 20,
  },
  reviewItem: {
    backgroundColor: '#0D192C',
    borderRadius: 10,
    padding: 14,
    marginBottom: 12,
    borderLeftWidth: 4,
  },
  reviewItemCorrect: {
    borderLeftColor: '#4cd137',
  },
  reviewItemIncorrect: {
    borderLeftColor: '#ff5252',
  },
  reviewItemHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  reviewNumber: {
    color: '#E5A93C',
    fontWeight: 'bold',
    fontSize: 13,
  },
  reviewStatus: {
    fontSize: 11,
    fontWeight: 'bold',
    textTransform: 'uppercase',
  },
  reviewStatusCorrect: {
    color: '#4cd137',
  },
  reviewStatusIncorrect: {
    color: '#ff5252',
  },
  reviewQuestionText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 8,
  },
  reviewCorrectAnswer: {
    color: '#8A99AD',
    fontSize: 13,
  },
  reviewYourAnswer: {
    color: '#ff5252',
    fontSize: 13,
    marginTop: 2,
  },
});
